// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUL7Qp3zEaPyxFhOJI7cw0rIHmhEo9Jw',
    appId: '1:839469063059:web:44351a5a7e3c3e7f18e666',
    messagingSenderId: '839469063059',
    projectId: 'bolajon-os-dd744',
    authDomain: 'bolajon-os-dd744.firebaseapp.com',
    storageBucket: 'bolajon-os-dd744.firebasestorage.app',
    measurementId: 'G-SVE5G5DNQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgdcSVpFOsDyumNhidofG9KElZJcikyY',
    appId: '1:839469063059:android:05015cb82dd4b56318e666',
    messagingSenderId: '839469063059',
    projectId: 'bolajon-os-dd744',
    storageBucket: 'bolajon-os-dd744.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhX4mJ9rLMlVPxXaTDSfnbdjbBjUl4gck',
    appId: '1:839469063059:ios:ff5b26ab91e489c718e666',
    messagingSenderId: '839469063059',
    projectId: 'bolajon-os-dd744',
    storageBucket: 'bolajon-os-dd744.firebasestorage.app',
    iosClientId: '839469063059-8eufpf5e11q4uhthrk3qm5imaloc2sok.apps.googleusercontent.com',
    iosBundleId: 'com.example.childOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEUL7Qp3zEaPyxFhOJI7cw0rIHmhEo9Jw',
    appId: '1:839469063059:web:bdcc1147865236b618e666',
    messagingSenderId: '839469063059',
    projectId: 'bolajon-os-dd744',
    authDomain: 'bolajon-os-dd744.firebaseapp.com',
    storageBucket: 'bolajon-os-dd744.firebasestorage.app',
    measurementId: 'G-CC97XST1WT',
  );
}
